//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GostsHotelApp.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public Bookings()
        {
            this.BookingServices = new HashSet<BookingServices>();
            this.Evictions = new HashSet<Evictions>();
        }
    
        public int BookingID { get; set; }
        public int GhostID { get; set; }
        public int RoomID { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public int TotalPrice { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Ghosts Ghosts { get; set; }
        public virtual Rooms Rooms { get; set; }
        public virtual ICollection<BookingServices> BookingServices { get; set; }
        public virtual ICollection<Evictions> Evictions { get; set; }
    }
}
