//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GostsHotelApp.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evictions
    {
        public int EvictionID { get; set; }
        public int BookingID { get; set; }
        public System.DateTime EvictionDate { get; set; }
        public string Reason { get; set; }
        public int ExecutorUserID { get; set; }
    
        public virtual Bookings Bookings { get; set; }
        public virtual Users Users { get; set; }
    }
}
