//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GostsHotelApp.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ghosts
    {
        public Ghosts()
        {
            this.Bookings = new HashSet<Bookings>();
            this.Users = new HashSet<Users>();
        }
    
        public int GhostID { get; set; }
        public string Name { get; set; }
        public int YearOfPassing { get; set; }
        public int TransparencyLevel { get; set; }
        public System.DateTime RegistrationDate { get; set; }
    
        public virtual ICollection<Bookings> Bookings { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
