//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GostsHotelApp.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomTypes
    {
        public RoomTypes()
        {
            this.Rooms = new HashSet<Rooms>();
        }
    
        public int TypeID { get; set; }
        public string TypeName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Rooms> Rooms { get; set; }
    }
}
