//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GostsHotelApp.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Evictions = new HashSet<Evictions>();
            this.Logs = new HashSet<Logs>();
        }
    
        public int UserID { get; set; }
        public string Login { get; set; }
        public string PasswordHash { get; set; }
        public int RoleID { get; set; }
        public Nullable<int> GhostID { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ICollection<Evictions> Evictions { get; set; }
        public virtual Ghosts Ghosts { get; set; }
        public virtual ICollection<Logs> Logs { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
